name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Build
        if: success()
        run: |
          pio run

      - name: Prepare files
        run: |
          set -x
          mkdir -p /tmp/dist

          for path in ./.pio/build/*/; do
            name="$(basename "${path}")"
            mv "./.pio/build/$name/firmware.hex" "/tmp/dist/$name.hex"
          done

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: /tmp/dist/*.hex
